apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: leaderelection-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leaderelection-role
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leaderelection-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leaderelection-role
subjects:
  - kind: ServiceAccount
    name: leaderelection-serviceaccount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: leaderelection-example
  name: leaderelection
spec:
  replicas: 5
  selector:
    matchLabels:
      app: leaderelection-example
  template:
    metadata:
      labels:
        app: leaderelection-example
    spec:
      automountServiceAccountToken: true
      serviceAccount: leaderelection-serviceaccount
      containers:
      - image: public.ecr.aws/q1p8v8z2/leaderelection-example
        name: leaderelection
        env:
          - name: POD_NAME
            valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace